name: Automate PR Reviews

on:
  pull_request:
    types: [opened, ready_for_review] # PR 생성 시 또는 Draft 상태에서 '리뷰 가능' 상태로 전환될 때 트리거되는 액션

jobs:
  # PR 작성자를 Assignee로 지정하고 Reviewer를 지정하는 작업
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Assignee와 Reviewer 할당을 위한 권한
    steps:
      - uses: hkusu/review-assign-action@v1 # https://github.com/hkusu/review-assign-action
        with:
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
          assignees: ${{ github.actor }} # PR 작성자를 assignee로 지정
          # Repository Variables에 정의한 값
          # - Settings > Secrets and Variables > Actions > Variables > Repository variables
          reviewers: ${{ vars.REVIEWERS }} # 리뷰할 수 있는 사람의 목록

  # PR에 라벨을 추가하고 이슈를 이동하는 작업
  automate-pr-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # PR에 라벨을 추가하고 이슈를 이동하기 위한 권한
      issues: read # 이슈 라벨을 읽어오기 위한 권한
    steps:
      # 액션에 필요한 파일을 가져오기 위한 작업
      - name: Checkout Action
        uses: actions/checkout@v4 # https://github.com/actions/checkout
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Github Actions에서 사용하는 기본 토큰
          fetch-depth: 1 # 가장 최근 커밋만 가져오기
          sparse-checkout: .github/actions # 액션 디렉토리만 가져오기

      # Node.js 환경 설정
      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      # PR에 라벨을 추가하는 작업
      - name: Sync labels from linked issues
        uses: ./.github/actions/sync-labels
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # PR을 Review Pipeline로 이동하는 작업
      - name: Move to Review Pipeline
        uses: ./.github/actions/zenhub-move-issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          zenhub_token: ${{ secrets.ZENHUB_TOKEN }}
          workspace_id: ${{ vars.ZENHUB_WORKSPACE_ID }} # https://github.com/ZenHubIO/API?tab=readme-ov-file#notes-1
          pipeline_id: ${{ vars.ZENHUB_REVIEW_PIPELINE_ID }}
